<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MyLovePixel.Commands</AssemblyName>
    <RootNamespace>MyLovePixel.Commands</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MyLovePixel.Core/MyLovePixel.Core.csproj" />
    <ProjectReference Include="../MyLovePixel.Tilemap/MyLovePixel.Tilemap.csproj" />
  </ItemGroup>
</Project>
