<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MyLovePixel.Recovery</AssemblyName>
    <RootNamespace>MyLovePixel.Recovery</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MyLovePixel.Persistence/MyLovePixel.Persistence.csproj" />
  </ItemGroup>
</Project>
