<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../MyLovePixel.Core/MyLovePixel.Core.csproj" />
    <ProjectReference Include="../MyLovePixel.Selection/MyLovePixel.Selection.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
</Project>
